<Project Sdk="Microsoft.NET.Sdk">
	<Sdk Name="ktsu.Sdk" />

	<ItemGroup>
		<PackageReference Include="ktsu.RunCommand" />
		<PackageReference Include="Polyfill" PrivateAssets="All" />
		<PackageReference Include="System.Memory" />
		<PackageReference Include="System.Threading.Tasks.Extensions" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="ktsu.SvnToGit.Test" />
	</ItemGroup>

</Project>
